# Generated by Django 6.0.8 on 2026-09-17 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('carga_horaria', models.PositiveIntegerField(default=20, help_text='Em horas')),
                ('horario', models.CharField(blank=True, max_length=120)),
                ('local', models.CharField(blank=True, default='IFPR - Campus Paranavaí', max_length=150)),
                ('vagas', models.PositiveIntegerField(default=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='cursos/')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('horario', models.TimeField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=180)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('publicado', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('especialidade', models.CharField(blank=True, max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='instrutores/')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('imagem', models.ImageField(upload_to='galeria/')),
                ('legenda', models.CharField(blank=True, max_length=240)),
                ('data', models.DateField(blank=True, null=True)),
                ('publicada', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('idade', models.PositiveIntegerField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aluno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=180)),
                ('data', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='core.curso')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='instrutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='core.instrutor'),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('CANCELADA', 'Cancelada')], default='ATIVA', max_length=10)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='core.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='core.curso')),
            ],
            options={
                'ordering': ['-data_matricula'],
            },
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='core.aula')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='core.matricula')),
            ],
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('aluno', 'curso'), name='matricula_unica'),
        ),
        migrations.AddConstraint(
            model_name='frequencia',
            constraint=models.UniqueConstraint(fields=('aula', 'matricula'), name='frequencia_unica'),
        ),
    ]
